apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wallarm-sidecar.name" . }}-webhook-certgen
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.admissionWebhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook-certgen
    {{- with .Values.admissionWebhook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
{{- end }}
  template:
    metadata:
      name: {{ include "wallarm-sidecar.name" . }}-webhook-certgen
    {{- if .Values.admissionWebhook.patch.podAnnotations }}
      annotations: {{ toYaml .Values.admissionWebhook.patch.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "wallarm-sidecar.labels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook-certgen
        {{- with .Values.admissionWebhook.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.admissionWebhook.patch.priorityClassName }}
      priorityClassName: {{ .Values.admissionWebhook.patch.priorityClassName }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      containers:
        - name: create
          {{- with .Values.admissionWebhook.patch.image }}
          image: "{{- if .repository -}}{{ .repository }}{{ else }}{{ .registry }}/{{ .image }}{{- end -}}:{{ .tag }}{{- if (.digest) -}} @{{.digest}} {{- end -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.admissionWebhook.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ include "wallarm-sidecar.name" . }}-webhook,{{ include "wallarm-sidecar.name" . }}-webhook.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name={{ include "wallarm-sidecar.name" . }}-webhook
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
          {{- if .Values.admissionWebhook.patch.resources }}
          resources: {{ toYaml .Values.admissionWebhook.patch.resources | nindent 12 }}
          {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "wallarm-sidecar.name" . }}-webhook
    {{- if .Values.admissionWebhook.nodeSelector }}
      nodeSelector: {{ toYaml .Values.admissionWebhook.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.admissionWebhook.patch.tolerations }}
      tolerations: {{ toYaml .Values.admissionWebhook.tolerations | nindent 8 }}
    {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.admissionWebhook.patch.runAsUser }}
        fsGroup: {{ .Values.admissionWebhook.patch.fsGroup }}
