apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wallarm-sidecar.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.admissionWebhook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
