apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallarm-sidecar.postanalytics.secret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.wallarmApi.token | b64enc | quote }}