apiVersion: v1
kind: Service
metadata:
  {{- if .Values.admissionWebhook.service.annotations }}
  annotations: {{ toYaml .Values.admissionWebhook.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.admissionWebhook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "wallarm-sidecar.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.admissionWebhook.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: webhook
    {{- if semverCompare ">=1.20" .Capabilities.KubeVersion.Version }}
      appProtocol: https
    {{- end }}
  selector:
    {{- include "wallarm-sidecar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
