apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "wallarm-sidecar.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
data:
  values.yaml: |
    api:
{{ .Values.wallarmApi | toYaml | indent 6 }}
    wallarm:
      tarantool:
        host: postanalitycs.{{ .Release.Namespace }}.cvs
        port: ""
{{ .Values.sidecarDefaults.wallarm | toYaml | indent 6 }}
    container:
{{ .Values.sidecarDefaults.container | toYaml | indent 6 }}

  template.yaml: |
    {{`{{- define "apiVariables"  }}
        - name: WALLARM_API_HOST
          value: {{ .Values.wallarmApi.host }}
        - name: WALLARM_API_PORT
          value: {{ .Values.wallarmApi.port }}
        - name: WALLARM_API_TOKEN
          value: {{ .Values.wallarmApi.token }}
        - name: WALLARM_API_USE_SSL
          value: {{ .Values.wallarmApi.useSSL }}
        - name: WALLARM_API_CA_VERIFY
          value: {{ .Values.wallarmApi.caVerify }}

        - name: WALLARM_MODE
          value: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/wallarm-mode" .Config.Wallarm.mode }}
        - name: NGINX_PORT
          value: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/wallarm-proxy-port" .Config.Wallarm.proxyPort }}
        - name: NGINX_BACKEND
          value: "127.0.0.1:{{ getAnnotation .ObjectMeta "sidecar.wallarm.io/wallarm-app-port" .Config.Wallarm.appPort}}"
        - name: POSTANALYTIC_ADDRESS
          value: {{ .Values.Wallarm.PostAnalyticsHost }}
        {{ if (isSet .ObjectMeta.Annotations "sidecar.wallarm.io/wallarm-app-id") -}}
        - name: WALLARM_APPLICATION
          value: {{ index .ObjectMeta.Annotations "sidecar.wallarm.io/wallarm-app-id" }}
        {{- end  }}
      {{- end  }}

        initContainers:
        volumes:
        containers:
        - name: wallarm-sidecar
          image: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/proxy-image" .Config.Container.image }}
          imagePullPolicy: IfNotPresent
          env:
          {{- template "environmentVariables" . }}
          ports:
            - containerPort: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/wallarm-proxy-port" .Values.Config.wallarm.proxyPort }}
          livenessProbe:
            tcpSocket:
              port: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/wallarm-proxy-port" .Values.Config.wallarm.proxyPort }}


          resources:
            requests:
              cpu: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/proxy-cpu" .Values.Proxy.Resources.Requests.Cpu }}
              memory: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/proxy-memory" .Values.Proxy.Resources.Requests.Memory }}
            limits:
              cpu: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/proxy-cpu-limit" .Values.Proxy.Resources.Limits.Cpu }}
              memory: {{ getAnnotation .ObjectMeta "sidecar.wallarm.io/proxy-memory-limit" .Values.Proxy.Resources.Limits.Memory }}`}}
