apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-helm-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: helm-hook
    {{- with .Values.controller.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ template "wallarm-sidecar.fullname" . }}-helm-hook
      annotations:
        {{- include "wallarm-sidecar.annotations" . | nindent 8 }}
        {{- with .Values.controller.extraAnnotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "wallarm-sidecar.labels" . | nindent 8 }}
        app.kubernetes.io/component: helm-hook
        {{- with .Values.controller.extraLabels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccount: {{ template "wallarm-sidecar.fullname" . }}-helm-hook
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - sh
            - '-c'
            - >-
              kubectl delete mutatingwebhookconfiguration {{ template "wallarm-sidecar.fullname" . }};
              kubectl delete secret {{ template "wallarm-sidecar.fullname" . }}-admission-tls --namespace {{ .Release.Namespace }};
      restartPolicy: Never
  backoffLimit: 2