{{- $tls := fromYaml (include "wallarm-sidecar.controller.certificates" . ) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.controller.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "wallarm-sidecar.fullname" . }}-controller
webhooks:
  - name: injector.sidecar.wallarm.io
    matchPolicy: Equivalent
    rules:
      - apiGroups: ["*"]
        apiVersions: ["v1"]
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ $tls.ca }}
      service:
        namespace: {{ .Release.Namespace | quote }}
        name: {{ template "wallarm-sidecar.fullname" . }}-controller
        path: "/inject"
    objectSelector:
      matchLabels:
        wallarm-sidecar: enabled

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wallarm-sidecar.fullname" . }}-controller
  annotations:
    {{- include "wallarm-sidecar.annotations" . | nindent 4 }}
    {{- with .Values.controller.extraAnnotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    {{- with .Values.controller.extraLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.crt }}
  tls.key: {{ $tls.key }}
  ca.crt: {{ $tls.ca }}
