apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: tarantool
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "wallarm-sidecar.postanalytics.cronConfig" . }}
  namespace: {{ .Release.Namespace }}
data:
  crontab: |
    {{- with .Values.postanalytics.helpers.cron.jobs.exportAttacks }}
    # export-attacks
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-attacks -l STDOUT
    {{- end }}

    {{- with .Values.postanalytics.helpers.cron.jobs.exportCounters }}
    # export-counters
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-counters -l STDOUT
    {{- end }}

    {{- with .Values.postanalytics.helpers.cron.jobs.exportEnvironment }}
    # export-environment
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/export-environment -l STDOUT
    {{- end }}

    {{- with .Values.postanalytics.helpers.cron.jobs.bruteDetect }}
    # brute-detect
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/brute-detect -l STDOUT
    {{- end }}

    {{- with .Values.postanalytics.helpers.cron.jobs.syncMarkers }}
    # sync-markers
    {{ .schedule }} timeout {{ .timeout }} /opt/wallarm/ruby/usr/share/wallarm-common/sync-markers -l STDOUT
    {{- end }}