apiVersion: v1
kind: Service
metadata:
  {{- if .Values.postanalytics.tarantool.service.annotations }}
  annotations: {{ .Values.postanalytics.tarantool.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: postanalytics
    {{- with .Values.postanalytics.tarantool.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: postanalytics
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: tarantool
      port: {{ template "wallarm-sidecar.postanalytics.tarantoolPort" . }}
      protocol: TCP
  selector:
    {{- include "wallarm-sidecar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postanalytics
