apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- with .Values.admissionWebhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.admissionWebhook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "wallarm-sidecar.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "wallarm-sidecar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admission-webhook
  replicas: {{ .Values.admissionWebhook.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webhook-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "wallarm-sidecar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      containers:
        - name: sidecar-injector
          {{- with .Values.admissionWebhook.image }}
          image: "{{ .registry }}/{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          args:
          - -port={{ .Values.admissionWebhook.port }}
          - -sidecar-template=/etc/webhook/config/sidecar-template.yaml
          - -sidecar-config=/etc/webhook/config/sidecar-config.yaml
          - -tls-cert=/usr/local/certificates/cert
          - -tls-key=/usr/local/certificates/key
          - -webhook-inject-path={{ .Values.admissionWebhook.injectPath }}
          - -webhook-health-path={{ .Values.admissionWebhook.healthPath }}
          volumeMounts:
            - name: webhook-config
              mountPath: /etc/webhook/config
              readOnly: true
            - name: webhook-cert
              mountPath: /usr/local/certificates
              readOnly: true
          ports:
            - name: webhook
              containerPort: {{ .Values.admissionWebhook.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.admissionWebhook.healthPath }}
              port: {{ .Values.admissionWebhook.port }}
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.admissionWebhook.healthPath }}
              port: {{ .Values.admissionWebhook.port }}
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          {{- if .Values.admissionWebhook.resources }}
          resources: {{ toYaml .Values.admissionWebhook.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: webhook-cert
          secret:
            secretName: {{ include "wallarm-sidecar.name" . }}-webhook
        - name: webhook-config
          configMap:
            name: {{ include "wallarm-sidecar.name" . }}-webhook
    {{- if .Values.admissionWebhook.nodeSelector }}
      nodeSelector: {{ toYaml .Values.admissionWebhook.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.admissionWebhook.tolerations }}
      tolerations: {{ toYaml .Values.admissionWebhook.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.admissionWebhook.affinity }}
      affinity: {{ toYaml .Values.admissionWebhook.affinity | nindent 8 }}
    {{- end }}