apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "wallarm-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "wallarm-sidecar.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
data:
  sidecar-values.yaml: |-
    api: {{ toYaml .Values.wallarmApi | nindent 6 }}
    wallarm: {{ toYaml .Values.sidecarDefaults.wallarm | nindent 6 }}
      tarantool:
        host: postanalytics.{{ .Release.Namespace }}.svc
    container: {{ toYaml .Values.sidecarDefaults.container | nindent 6 }}
    deployment: {{ toYaml .Values.sidecarDefaults.deployment | nindent 6 }}
{{ (.Files.Glob "files/sidecar-template.yaml").AsConfig | indent 2 }}