name: Test artifacts

on:
  push:
    branches: [ "main", "helm-chart", "github-actions" ]
    tags:
      - '**'
#  pull_request:
#    branches: [ "main" ]
#
#
  workflow_dispatch:

env:
  KUBEVAL_SCHEMA_LOCATION: 'https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/'


jobs:
  lint:
    name: Test artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm lint
        run: |
          helm version
          helm lint . --debug

      - name: Helm template
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm template . > result.yaml --debug
        
      - name: Kubeval
        uses: instrumenta/kubeval-action@master
        with:
          files: result.yaml
          version: 1.21.5
          ignore_missing_schemas: false

